version: '3.8'

services:
  psql:
    image: postgres:latest
    container_name: psql
    environment:
      POSTGRES_DB: gameapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ciro
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
